[browser]
gatherUsageStats = false

[theme]
# 라이트 모드 색상
base = "light"
primaryColor = "#0052D4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
enableStaticServing = true
